var signs = [
  //mandatory

  {"sign": "Stop", "img": "r1.png"},
  {"sign": "Give way", "img": "r3.png"},
  {"sign": "One way", "img": "r4.png"},
  {"sign": "One-way", "img": "r24.png"},
  {"sign": "Vehicles prohibited in both directions", "img": "r80.png"},
  {"sign": "U-turn prohibited", "img": "r5.png"},
  {"sign": "Right turn prohibited", "img": "r8.png"},
  {"sign": "Horn prohibited", "img": "r9.png"},
  {"sign": "Overtaking prohibited", "img": "r17.png"},
  {"sign": "No entry", "img": "r19.png"},
  {"sign": "No entry for motor vehicles", "img": "r25.png"},
  {"sign": "Trucks Prohibited", "img": "r26.png"},
  {"sign": "Bullock cart prohibited", "img": "r27.png"},
  {"sign": "Bullock cart & Hand cart prohibited", "img": "r81.png"},
  {"sign": "Tonga Prohibited", "img": "r82.png"},
  {"sign": "Hand cart prohibited", "img": "r83.png"},
  {"sign": "Cycle Prohibited", "img": "r84.png"},
  {"sign": "Pedestrians prohibited", "img": "r28.png"},
  {"sign": "Left turn Prohibited", "img": "r29.png"},
  {"sign": "Drive the vehicle not exceeding 50 km/hr.", "img": "r30.png"},
  {
    "sign": "No entry for vehicles having more than 2 meters width.",
    "img": "r31.png"
  },
  {
    "sign": "Entry for vehicles having height not exceeding 3.5 meters.",
    "img": "r32.png"
  },
  {"sign": "Length Limit", "img": "r85.png"},

  {"sign": "Load Limit", "img": "r87.png"},
  {"sign": "Axle weight limit", "img": "r43.png"},
  {"sign": "No parking", "img": "r23.png"},
  {"sign": "No Stopping or standing", "img": "r33.png"},
  {"sign": "End of speed restriction", "img": "r14.png"},
  {"sign": "Compulsory turn left", "img": "r2.png"},
  {"sign": "Ahead only", "img": "r34.png"},
  {"sign": "Compulsory ahead or turn left", "img": "r35.png"},
  {"sign": "Compulsory keep left", "img": "r36.png"},
  {"sign": "Compulsory go ahead or turn to right", "img": "r52.png"},
  {"sign": "Sound horn compulsory", "img": "r21.png"},
  {"sign": "Compulsory turn right", "img": "r22.png"},
  {"sign": "Compulsory Cycle Track", "img": "r86.png"},

//Cautionary

  {"sign": "Right Hand Curve", "img": "r37.png"},
  {"sign": "Left Hand Curve", "img": "r38.png"},
  {"sign": "Right Hair Pin Bend", "img": "r39.png"},
  {"sign": "Left Hair Pin Bend", "img": "r40.png"},
  {"sign": "Right Reverse Bend", "img": "r41.png"},
  {"sign": "Left Reverse Bend", "img": "r42.png"},
  {"sign": "Left Side Road", "img": "r20.png"},
  {"sign": "Right Side Road", "img": "r40.png"},
  {"sign": "Cross Road", "img": "r18.png"},
  {"sign": "'T' Intersection", "img": "r45.png"},
  {"sign": "Round About", "img": "r46.png"},
  {"sign": "Dangerous Dip", "img": "r47.png"},
  {"sign": "Y-intersection left", "img": "r49.png"},
  {"sign": "Y-intersection right", "img": "r50.png"},
  {"sign": "Y-intersection", "img": "r51.png"},
  {"sign": "Slippery Road", "img": "r53.png"},
  {"sign": "Staggered Intersection\n(Left-Right)", "img": "r88.png"},
  {"sign": "Staggered Intersection\n(Right-Left)", "img": "r89.png"},
  {"sign": "Loose Gravel", "img": "r54.png"},
  {"sign": "Cycle Crossing", "img": "r55.png"},
  {"sign": "Pedestrian Crossing", "img": "r6.png"},
  {"sign": "Possibility of cattle on road", "img": "r56.png"},
  {"sign": "School Ahead", "img": "r57.png"},
  {"sign": "Men at work", "img": "r58.png"},
  {"sign": "Falling Rocks", "img": "r59.png"},
  {"sign": "Ferry", "img": "r60.png"},
  {"sign": "Steep Ascent", "img": "r61.png"},
  {"sign": "Steep Descent", "img": "r62.png"},
  {"sign": "Narrow Bridge", "img": "r10.png"},
  {"sign": "Narrow Road Ahead", "img": "r15.png"},
  {"sign": "Road Widens Ahead", "img": "r63.png"},
  {"sign": "Gap in Median", "img": "r64.png"},
  {"sign": "Barrier Ahead", "img": "r66.png"},
  {"sign": "Humb or Rough Road", "img": "r65.png"},
  {"sign": "Unguarded Railway Crossing (100 mts)", "img": "r90.png"},
  {"sign": "Unguarded Railway Crossing (200 mts)", "img": "r16.png"},
  {"sign": "Guarded Railway Crossing (100 mts)", "img": "r91.png"},
  {"sign": "Guarded Railway Crossing (200 mts)", "img": "r48.png"},

  //Informatory

  {"sign": "Public Telephone", "img": "r93.png"},
  {"sign": "Petrol Pump", "img": "r94.png"},
  {"sign": "Hospital", "img": "r11.png"},
  {"sign": "First Aid Post", "img": "r12.png"},
  {"sign": "Eating Place", "img": "r95.png"},
  {"sign": "Light Refreshment", "img": "r96.png"},
  {"sign": "Resting Place", "img": "r13.png"},
  {"sign": "No Through Side Road", "img": "r67.png"},
  {"sign": "No Through Road", "img": "r68.png"},
  {"sign": "Park This Side", "img": "r7.png"},
  {"sign": "Parking Both Side", "img": "r69.png"},
  {"sign": "Scooter & Motorcycle Stand", "img": "r70.png"},
  {"sign": "Cycle Stand", "img": "r71.png"},
  {"sign": "Taxi Stand", "img": "r71.png"},
  {"sign": "Autorickshaw Stand", "img": "r72.png"},
];
